ALTER TABLE "ReadingContent"
ADD COLUMN "author" TEXT NOT NULL DEFAULT '',
ADD COLUMN "description" TEXT NOT NULL DEFAULT '',
ADD COLUMN "coverUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "sourceFileType" TEXT NOT NULL DEFAULT '',
ADD COLUMN "sourceFileName" TEXT NOT NULL DEFAULT '';
